/* TOSMC 4.9.2-HF12-HF26-TEST19-HF2 — Landgang V2.1 controller. */
(()=>{'use strict';const trigger=document.getElementById('landgang-link'),layer=document.getElementById('outro-layer');if(!trigger||!layer)return;let running=false,audioContext=null;
function ctx(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audioContext)audioContext=new C();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});return audioContext}
function noise(c,s){const b=c.createBuffer(1,Math.floor(c.sampleRate*s),c.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){last=last*.78+(Math.random()*2-1)*.22;d[i]=last}return b}
function coinChime(c,t,out){[0,.09,.19].forEach((o,i)=>{const osc=c.createOscillator(),g=c.createGain();osc.type='sine';osc.frequency.value=[1280,1620,1060][i];g.gain.setValueAtTime(.0001,t+o);g.gain.exponentialRampToValueAtTime(.035,t+o+.01);g.gain.exponentialRampToValueAtTime(.0001,t+o+.32);osc.connect(g).connect(out);osc.start(t+o);osc.stop(t+o+.34)})}
function creak(c,t,out){const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=noise(c,1.45);f.type='bandpass';f.frequency.setValueAtTime(480,t);f.frequency.exponentialRampToValueAtTime(145,t+1.4);f.Q.value=.8;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.16,t+.18);g.gain.setValueAtTime(.11,t+.9);g.gain.exponentialRampToValueAtTime(.0001,t+1.42);s.connect(f).connect(g).connect(out);s.start(t);s.stop(t+1.45)}
function slam(c,t,out){const sub=c.createOscillator(),sg=c.createGain();sub.type='sine';sub.frequency.setValueAtTime(92,t);sub.frequency.exponentialRampToValueAtTime(38,t+.32);sg.gain.setValueAtTime(.72,t);sg.gain.exponentialRampToValueAtTime(.0001,t+.38);sub.connect(sg).connect(out);sub.start(t);sub.stop(t+.4);const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=noise(c,.2);f.type='bandpass';f.frequency.value=780;f.Q.value=.8;g.gain.setValueAtTime(.62,t);g.gain.exponentialRampToValueAtTime(.0001,t+.17);n.connect(f).connect(g).connect(out);n.start(t);n.stop(t+.2);const m=c.createOscillator(),mg=c.createGain();m.type='triangle';m.frequency.setValueAtTime(220,t);m.frequency.exponentialRampToValueAtTime(126,t+.2);mg.gain.setValueAtTime(.14,t);mg.gain.exponentialRampToValueAtTime(.0001,t+.24);m.connect(mg).connect(out);m.start(t);m.stop(t+.25)}
function soundtrack(){const c=ctx();if(!c)return;const t=c.currentTime+.03,master=c.createGain();master.gain.setValueAtTime(.78,t);master.gain.setValueAtTime(.78,t+2.25);master.gain.exponentialRampToValueAtTime(.0001,t+2.75);master.connect(c.destination);coinChime(c,t+.12,master);creak(c,t+.68,master);slam(c,t+1.90,master)}
function finish(){try{window.close()}catch(_){}window.setTimeout(()=>layer.classList.add('is-fallback'),180)}
function start(e){e&&e.preventDefault();if(running)return;running=true;document.body.classList.add('is-outro-active');layer.className='outro-layer is-active';layer.setAttribute('aria-hidden','false');layer.focus({preventScroll:true});soundtrack();setTimeout(()=>layer.classList.add('is-half'),700);setTimeout(()=>layer.classList.add('is-ready'),1550);setTimeout(()=>layer.classList.add('is-slam'),1900);setTimeout(()=>layer.classList.add('is-after'),2120);setTimeout(finish,2750)}trigger.addEventListener('click',start)})();
